# Versioning
version: 2

 # OS, Phyton, and Others
build:
   os: ubuntu-22.04
   atp_packages:
    - libclang
    - cmake
   tools:
     python: "3.12"

# MKDocs
mkdocs:
   configuration: mkdocs.yml

# Phyton requirements
python:
   install:
   - requirements: docs/requirements.txt 
