# Versioning
version: 2

# Builds
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# MKDocs Configuration
mkdocs:
  configuration: mkdocs.yml

# Phyton Requirements
python:
   install:
   - requirements: docs/requirements.txt