[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MKDocs-RTD-Tutorial"
authors = [{name = "Skrillx", email = "skrillx1300@gmail.com"}]
dynamic = ["version", "description"]